config/routes.rb
Rails.application.routes.draw do

	root 'questions#index'
  

  post 'questions/:id' => 'questions#show'
  delete 'attempts' => 'attempts#destroy_all'
  
  resources :questions
  resources :answers
  resources :attempts
  resources :progresses
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base

	def self.save_matches(level, user, matches)
		for match in matches
			# save only if not present
			attempt = Attempt.new(:level => level, :value => match, :who => user, :when => Time.now)
			attempt.save
		end
	end
end

app/models/progress.rb
class Progress < ActiveRecord::Base
    validates :level, numericality: { only_integer: true }
end

app/models/question.rb
class Question < ActiveRecord::Base
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def index
		@answers = Answer.all
    end

    def show
		@answer = Answer.find(params[:id])
    end

    def new
		@answer = Answer.new
    end

    def edit
		@answer = Answer.find(params[:id])
    end

    def create     
        @answer = Answer.new(answer_params)
        
        if @answer.save
    	    redirect_to @answer
    	else
    	    render 'new'
    	end
    end

    def update
		@answer = Answer.find(params[:id])
		
		if @answer.update(answer_params)
			redirect_to @answer
		else
			render 'edit'
		end
    end

    def destroy
		@answer = Answer.find(params[:id])
		@answer.destroy
		
		redirect_to answers_path
    end

    private
	def answer_params
	    params.require(:answer).permit(:level, :value, :positive)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

	def index
		@attempts = Attempt.all
	end
	
	def destroy
	@attempt = Attempt.find(params[:id])
	@attempt.destroy
	
	redirect_to attempts_path
    end
	
	def destroy_all
	Attempt.destroy_all
	
	redirect_to attempts_path
    end
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController

    def index
	@progresses = Progress.all
    end

    def show
	#@progress = Progress.find(params[:level])
	@progress = Progress.find_by! level: params[:level]
    end

    def new
	@progress = Progress.new
    end

    def edit
	#@progress = Progress.find(params[:level])
	@progress = Progress.find_by! level: params[:level]
    end

    def create
        #render plain: params[:progress].inspect        
        @progress = Progress.new(progress_params)
        
        if @progress.save
    	    redirect_to @progress
    	else
    	    render 'new'
    	    #redirect_to new_progress_path
    	end
    end

    def update
	#@progress = Progress.find(params[:level])
	@progress = Progress.find_by! level: params[:level]
	
	if @progress.update(progress_params)
	    redirect_to @progress
	else
	    render 'edit'
	end
    end

    def destroy
	#@progress = Progress.find(params[:level])
	@progress = Progress.find_by! level: params[:level]
	@progress.destroy
	
	redirect_to progresses_path
    end

    private
	def progress_params
	    params.require(:progress).permit(:user, :level)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end
  
  def show
	level = params[:id].to_i
	user = session.id
    @question = get_current_question
	dbpatterns = Answer.where(level: level).order(id: :asc)
	if ( params[:commit] != nil )
		matches = verify reduce(params[:attempt]), dbpatterns
		Attempt.save_matches(level, user, matches)
	end
	@status = get_level_status(level, user)
  end
  
  def new
    @question = Question.new
	_last = Question.order(level: :asc).last
	if _last == nil
		@question.level = 1
	else
		@question.level = _last.level + 1
	end
  end
  
  def edit
	@question = get_current_question
  end
  
  def update
	@question = get_current_question
	
	if @question.update(question_params)
	    redirect_to @question
	else
	    render 'edit'
	end
  end
  
  def create
    @question = Question.new(question_params)
	@question.save
	redirect_to @question
  end
  
  private
	def verify(candidate, answers)
		# html in the controller - like a shit!
		@debug = "<b>Value:</b><a> #{candidate}</a><br/><br/>"
		i = 0
		if ( candidate == nil )
			candidate = ""
		end
		matches = Array.new
		begin
			if ( candidate =~ Regexp.new(answers[i].value) )
				matches.push(answers[i].id)
				color = "#99FF99"
				# TODO break loop if can match only one
			else
				color = ""
			end
			@debug += "<a style=\"background-color: #{color}\">" + answers[i].value + "</a><br/>"
			i += 1
		end until i == answers.size
		# TODO return match indexes
		return matches
	end
  
	def get_current_question
		_id = params[:id].to_i
		return Question.find_by(level: _id)
	end
  
	def question_params
	    params.require(:question).permit(:level, :content, :qtype)
	end
	
	def reduce val
		if (val == nil)
			return ""
		end
		
		if ( val.is_a?(String) )
			return val
		else
			return val.join("")
		end
	end
	
	def get_level_status(level, user)
		answers = Answer.where(level: params[:id].to_i).order("positive desc, id asc")
		attempts = Attempt.where(level: level, who: user)
		
		@solved = Array.new
		for attempt in attempts
			@solved.push(attempt.value)
		end
		
		status = Array.new
		for answer in answers
			if ( @solved.include? answer.id )
				if ( answer.positive )
					status.push(1)
				else
					status.push(-1)
				end
			else
				if ( answer.positive )
					status.push(2)
				else
					status.push(-2)
				end
			end
		end
		return status
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def metro_check_box(name, value, text)
		str = "<label class=\"input-control checkbox small-check\">"
		str += check_box_tag(name, value)
		str += "<span class=\"check\"></span>"\
			   "<span class=\"caption\">#{text}</span>"\
			   "</label>"
		str.html_safe
	end
	
	def metro_radio_button(name, value, text)
		str = "<label class=\"input-control radio small-check\">"
		str += radio_button_tag(name, value)
		str += "<span class=\"check\"></span>"\
			   "<span class=\"caption\">#{text}</span>"\
			   "</label>"
		str.html_safe
	end
	
	def metro_text_field(name)
		str = "<div class=\"input-control text\">"
		str += text_field_tag(name)
		str += "</div>"
		str.html_safe
	end
	
	def metro_number_field(name)
		str = "<div class=\"input-control text\">"
		str += number_field_tag(name, nil, max: 5)
		str += "</div>"
		str.html_safe
	end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	
	def level_status(data)
		str = "<div class=\"status\">"
		for i in data
			case i
			when -2
				str += image_tag("negative_inactive.png")
			when -1
				str += image_tag("negative_active.png")
			when 2
				str += image_tag("positive_inactive.png")
			when 1
				str += image_tag("positive_active.png")
			end			
		end
		str+= "</div>"
		str.html_safe
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@answer.errors.count, "error") %> prohibited
        this answer from being saved:
      </h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :level, "Level" %><br>
    <%= f.text_field :level %>
  </p>
 
  <p>
    <%= f.label :value, "Value" %><br>
    <%= f.text_area :value %>
  </p>
 
  <p>
    <%= f.label :positive, "Positive" %><br>
    <%= f.check_box :positive %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Answers</h1>

<%= link_to 'New answer', new_answer_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Level</th>
    <th>Value</th>
	<th>Positive</th>
  </tr>
 
  <% @answers.each do |answer| %>
    <tr>
      <td><%= answer.id %></td>
      <td><%= answer.level %></td>
      <td><%= answer.value %></td>
	  <td><%= answer.positive %></td>
      <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
      <td><%= link_to 'Destroy', answer_path(answer),
    		method: :delete,
    		data: { confirm: 'Are you sure?'}  %></td>
    </tr>
  <% end %>
</table>

app/views/answers/show.html.erb
<p>
  <strong>Level:</strong>
  <%= @answer.level %>
</p>
 
<p>
  <strong>Value:</strong>
  <%= @answer.value %>
</p>

<p>
  <strong>Positive:</strong>
  <%= @answer.positive %>
</p>

<%= link_to 'Answers', answers_path %>

app/views/attempts/index.html.erb
<h1>Attempts</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Level</th>
    <th>Value</th>
	<th>User</th>
	<th>When</th>
  </tr>
 
  <% @attempts.each do |attempt| %>
    <tr>
      <td><%= attempt.id %></td>
      <td><%= attempt.level %></td>
      <td><%= attempt.value %></td>
	  <td><%= attempt.who %></td>
	  <td><%= attempt.when %></td>
	  <td><%= link_to 'Destroy', attempt_path(attempt),
    		method: :delete,
    		data: { confirm: 'Are you sure?'}  %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Destroy ALL', attempts_path(),
    		method: :delete,
    		data: { confirm: 'ARE YOU FUCKING SURE????'}  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/progresses/_form.html.erb
<%= form_for @progress do |f| %>

  <% if @progress.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@progress.errors.count, "error") %> prohibited
        this progress from being saved:
      </h2>
      <ul>
        <% @progress.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :user, "User ID" %><br>
    <%= f.text_field :user %>
  </p>
 
  <p>
    <%= f.label :level, "User level" %><br>
    <%= f.text_area :level %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render 'form' %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<h1>Listing progresses</h1>

<%= link_to 'Quiz', controller: 'progresses' %>
<%= link_to 'New progress', new_progress_path %>

<table>
  <tr>
    <th>ID</th>
    <th>User ID</th>
    <th>User Level</th>
  </tr>
 
  <% @progresses.each do |progress| %>
    <tr>
      <td><%= progress.id %></td>
      <td><%= progress.user %></td>
      <td><%= progress.level %></td>
      <td><%= link_to 'Show', progress_path(progress.level) %></td>
      <td><%= link_to 'Edit', edit_progress_path(progress.level) %></td>
      <td><%= link_to 'Destroy', progress_path(progress.level),
    		method: :delete,
    		data: { confirm: 'Are you sure?'}  %></td>
    </tr>
  <% end %>
</table>

app/views/progresses/new.html.erb
<h1>New progress</h1>

<%= render 'form' %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p>
  <strong>User ID:</strong>
  <%= @progress.user %>
</p>
 
<p>
  <strong>User Level:</strong>
  <%= @progress.level %>
</p>

<p>
    <strong>ID:</strong>
    <%= @progress.id %>
</p>

<%= link_to 'Back', new_progress_path %>
<%= link_to 'Edit', edit_progress_path(@progress.level) %>
<%= link_to 'Quiz', progresses_path %>

app/views/questions/_debug.html.erb
<p>
	<b>Debug:</b>
	<p><%= raw @debug %></p>
</p>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </p>
  
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  
  <p>
    <%= f.label :qtype %><br>
    <%= f.text_field :qtype %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Level</th>
    <th>Content</th>
	<th>Type</th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.level %></td>
      <td><%= question.content %></td>
	  <td><%= question.qtype %></td>
	  <td><%= link_to 'Show', question_path(question) %></td>
	  <td><%= link_to 'Edit', edit_question_path(question) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New question', new_question_path %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="base">
	<%= form_tag do %>
		<div class="content">
			<%= level_status(@status) %>
			<% case @question.qtype
				when "radio" %>
					<%= metro_radio_button(:attempt, :checked, " wide choice") %>
				<% when "check" %>
					<div class="checkbox-container">
						<%= metro_check_box "attempt[]", "a", " malachite" %><br>
						<%= metro_check_box "attempt[]", "b", " jasper" %><br>
						<%= metro_check_box "attempt[]", "c", " rhodonite" %><br>
						<%= metro_check_box "attempt[]", "d", " emerald" %>
					</div>
				<% when "number" %>
					<%= metro_number_field(:attempt) %>
				<% when "text" %>
					<%= metro_text_field(:attempt) %>
				<% else %>
					<a>Ooops!</a><br>
			<% end %>	
		</div>
		<div>
			<%= submit_tag("Try") %>
		</div>
	<% end %>
</div>

<%= link_to 'Questions', questions_path %>
<%= render 'debug' %>
<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h2>Vsem Baltimor<h2>
<p>Find me in app/views/welcome/index.html.erb</p>